spring:
  application:
    name: EPharmacy-MessageMS
  # datasource:
  #   url: 
  #   username: root
  #   password: root
  # jpa:
  #   hibernate:
  #     ddl-auto: ipdate
  cloud:
    consul:
      discovery:
        hostname: consul
        port: 8500
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: message-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.infy.message.dto.PaymentDTO
        spring.json.use.type.headers: false       
server:
  port: 6600
#   servlet:
#     context-path: /epharmacy 
