spring:
  application:
    name: EPharmacy-MessageMS

  cloud:
    consul:
      port: 8500
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true



  kafka:
    bootstrap-servers: localhost:9092

    topic:
      name: card-event

    consumer:
      group-id: card-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.infy.message.dto.CardDTO
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        
      
# app:
#   kafka:
#     topics:
#       card-topic: card-event
#       payment-topic: payment-event

# # Card Consumer Configuration
# card:
#   kafka:
#     consumer:
#       group-id: card-group

# # Payment Consumer Configuration
# payment:
#   kafka:
#     consumer:
#       group-id: payment-group


      # properties:
      #   "spring.json.trusted.packages": "*"
      #   "spring.json.use.type.headers": false
      #   "spring.json.value.default.type": com.infy.message.dto.PaymentDTO    
   
server:
  port: 6600
#   servlet:
#     context-path: /epharmacy 




