spring:
  application:
    name: EPharmacy_CustomerMS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/EPHARMACY_CUSTOMERMS_DB?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      host: localhost
      discovery: 
        enabled: true
        hostname: localhost
        register: true
        service-name: EPharmacy_CustomerMS
  
server:
  port: 6100
  servlet:
    context-path: /epharmacy
