server:
 port: 6000

spring:
  application:
    name: Epharmacy_Gateway
  cloud:
    consul:
      discovery:
        register: true
        hostname: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EPharmacy-CustomerMS
          uri: lb://EPharmacy-CustomerMS
          predicates:
            - Path=/epharmacy/customer-api/**
        - id: EPharmacy-MedicineMS
          uri: lb://EPharmacy-MedicineMS
          predicates:
            - Path=/epharmacy/medicine-api/medicines/**
        - id: Epharmacy-CartMS
          uri: lb://Epharmacy-CartMS
          predicates:
            - Path=/epharmacy/cart-api/**
            
         
      
          