DROP DATABASE if exists EPharmacy_OrderMS_DB;
CREATE DATABASE EPharmacy_OrderMS_DB;
USE EPharmacy_OrderMS_DB;

CREATE TABLE ORDER_DETAILS(
	ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
	MRP_TOTAL DECIMAL(7,2),
	DISCOUNT_PERCENT INT,
	DISCOUNTED_TOTAL DECIMAL(7,2),
	DELIVERY_DATE DATETIME,
	CUSTOMER_ID INT,
	ORDER_STATUS ENUM('PROCESSING','CONFIRMED','CANCELLED','COMPLETED'),
	ORDER_DATE DATETIME,
	CANCEL_REASON VARCHAR(500),
	ADDRESS_ID INT,
	DELIVERY_STATUS ENUM('AWAITING_CONFIRMATION','DELIVERED','IN_TRANSIT','OUT_FOR_DELIVERY','CANCELLED'),
	CARD_ID VARCHAR(16)
);

CREATE TABLE ORDERED_MEDICINE(
	ORDERED_MEDICINE_ID INT PRIMARY KEY AUTO_INCREMENT,
	ORDERED_QUANTITY INT,
	ORDER_SUBTOTAL DECIMAL(7,2) ,
	MEDICINE_ID INT,
	ORDER_ID INT REFERENCES ORDER_DETAILS(ORDER_ID)
);


commit;
