DROP DATABASE if exists EPHARMACY_CARTMS_DB;
CREATE DATABASE EPHARMACY_CARTMS_DB;
USE EPHARMACY_CARTMS_DB;

CREATE TABLE CUSTOMER_CART (
	CART_ID INT AUTO_INCREMENT,
    CUSTOMER_ID INT,
    MEDICINE_ID INT,
    QUANTITY SMALLINT,
	CONSTRAINT CART_ID_PK PRIMARY KEY (CART_ID)
);

INSERT INTO CUSTOMER_CART (CART_ID, CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (7300,  101, 1011, 2);
INSERT INTO CUSTOMER_CART (CART_ID, CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (7301,  102, 1020, 1);
INSERT INTO CUSTOMER_CART (CART_ID, CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (7302,  103, 1030, 1);
INSERT INTO CUSTOMER_CART (CART_ID, CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (7303,  104, 1030, 1);
INSERT INTO CUSTOMER_CART (CART_ID, CUSTOMER_ID, MEDICINE_ID, QUANTITY) VALUES (7304,  105, 1022, 3);

SELECT * FROM CUSTOMER_CART;

commit;
